configfile: "config.yaml"

from os.path import join, basename, splitext

WD = config['wd']
GENOMES_DIR = join(WD, config['genomes'])
FASTQ_DIR = join(WD, config['fastq'])
FEATURES_DIR = join(WD, config['features'])

WC = glob_wildcards(os.path.join(GENOMES_DIR, "{taxon}.fasta.gz"))

TAXA = WC.taxon
PAIRS = ['R1', 'R2']

rule all:
    input:
        expand("{features_dir}/{{taxon}}.{{pair}}.{{k}}mer.tsv.gz".format(features_dir=FEATURES_DIR),
               taxon=TAXA, pair=PAIRS, k=['5'])
    run:
        print("FINISHED WITH NO EXCEPTIONS!")


rule simulate_reads:
    input:
        "{genomes_dir}/{{taxon}}.fasta.gz".format(genomes_dir=GENOMES_DIR)
    output:
        f1 = "{fastq_dir}/{{taxon}}.R1.fastq.gz".format(fastq_dir=FASTQ_DIR),
        f2 = "{fastq_dir}/{{taxon}}.R2.fastq.gz".format(fastq_dir=FASTQ_DIR)
    shell:
        "python scripts/simulate_reads.py {fastq_dir} {{input}} {{output}}".format(fastq_dir=FASTQ_DIR)


rule extract_features_3mer:
    input:
        fastq="{fastq_dir}/{{taxon}}.{{pair}}.fastq.gz".format(fastq_dir=FASTQ_DIR),
        taxonomy=config['taxonomy']
    output:
        "{features_dir}/{{taxon}}.{{pair}}.3mer.tsv.gz".format(features_dir=FEATURES_DIR)
    shell:
        "python scripts/sequence_features.py {input.fastq} {input.taxonomy} {output} 3"


rule extract_features_4mer:
    input:
        fastq="{fastq_dir}/{{taxon}}.{{pair}}.fastq.gz".format(fastq_dir=FASTQ_DIR),
        taxonomy=config['taxonomy']
    output:
        "{features_dir}/{{taxon}}.{{pair}}.4mer.tsv.gz".format(features_dir=FEATURES_DIR)
    shell:
        "python scripts/sequence_features.py {input.fastq} {input.taxonomy} {output} 4"


rule extract_features_5mer:
    input:
        fastq="{fastq_dir}/{{taxon}}.{{pair}}.fastq.gz".format(fastq_dir=FASTQ_DIR),
        taxonomy=config['taxonomy']
    output:
        "{features_dir}/{{taxon}}.{{pair}}.5mer.tsv.gz".format(features_dir=FEATURES_DIR)
    shell:
        "python scripts/sequence_features.py {input.fastq} {input.taxonomy} {output} 5"


rule extract_features_6mer:
    input:
        fastq="{fastq_dir}/{{taxon}}.{{pair}}.fastq.gz".format(fastq_dir=FASTQ_DIR),
        taxonomy=config['taxonomy']
    output:
        "{features_dir}/{{taxon}}.{{pair}}.6mer.tsv.gz".format(features_dir=FEATURES_DIR)
    shell:
        "python scripts/sequence_features.py {input.fastq} {input.taxonomy} {output} 6"